"""Create customer_registrations table

Revision ID: 3526e89c8cb2
Revises: 
Create Date: 2025-03-20 15:14:20.072085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3526e89c8cb2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('search_log_id', sa.Integer(), nullable=True),
    sa.Column('transaction_number', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('transaction_amount', sa.String(length=50), nullable=True),
    sa.Column('euro_equivalent', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('document_issue_place', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('salary_origin', sa.String(length=100), nullable=True),
    sa.Column('transaction_intent', sa.Text(), nullable=True),
    sa.Column('transaction_nature', sa.String(length=50), nullable=True),
    sa.Column('suspicious', sa.String(length=1), nullable=True),
    sa.Column('agent_observations', sa.Text(), nullable=True),
    sa.Column('doc_notes', sa.Text(), nullable=True),
    sa.Column('document_paths', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_registrations_id'), 'customer_registrations', ['id'], unique=False)
    op.add_column('search_logs', sa.Column('user_decision', sa.String(length=20), nullable=True))
    op.alter_column('search_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_search_logs_id'), 'search_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_logs_id'), table_name='search_logs')
    op.alter_column('search_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('search_logs', 'user_decision')
    op.drop_index(op.f('ix_customer_registrations_id'), table_name='customer_registrations')
    op.drop_table('customer_registrations')
    # ### end Alembic commands ###
